<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <ProjectReference Include="../../src/EmbedIO/EmbedIO.csproj" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="all" />
    <Compile Include="../Shared/BasicAuthenticationSmoke.cs" Link="BasicAuthenticationSmoke.cs" />
  </ItemGroup>
</Project>
