"""HTTP/2 conformance cases and stateful campaign (development-only).

The client side is hyper-h2, an independent HTTP/2 implementation; malformed and
abusive inputs are written as raw frames with hyperframe so the server's reaction
can be observed without h2 state enforcement. Every response body is checked.

Usage:
  python -I h2_campaign.py cases --host H --port P [--tls] [--out FILE]
  python -I h2_campaign.py fuzz  --host H --port P --seed S --iterations N [--tls] [--out FILE]
Exit status is 1 when any violation, error or failed invariant is recorded.
"""

import argparse
import hashlib
import json
import random
import select
import socket
import ssl
import struct
import sys
import time

import h2.config
import h2.connection
import h2.events
import h2.exceptions
import h2.settings
from hyperframe import frame as hf

PREFACE = b"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"
FILE_LENGTH = 100_000
ERROR_NAMES = {0: "NO_ERROR", 1: "PROTOCOL_ERROR", 2: "INTERNAL_ERROR", 3: "FLOW_CONTROL_ERROR", 4: "SETTINGS_TIMEOUT",
               5: "STREAM_CLOSED", 6: "FRAME_SIZE_ERROR", 7: "REFUSED_STREAM", 8: "CANCEL", 9: "COMPRESSION_ERROR",
               10: "CONNECT_ERROR", 11: "ENHANCE_YOUR_CALM", 12: "INADEQUATE_SECURITY", 13: "HTTP_1_1_REQUIRED"}


def file_bytes():
    return bytes((i * 31 + (i >> 8)) & 0xFF for i in range(FILE_LENGTH))


class Endpoint:
    def __init__(self, host, port, tls, authority):
        self.host, self.port, self.tls, self.authority = host, port, tls, authority

    def connect(self, timeout=5.0):
        sock = socket.create_connection((self.host, self.port), timeout=timeout)
        sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
        if self.tls:
            context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
            context.check_hostname = False
            context.verify_mode = ssl.CERT_NONE  # Test certificate generated by the host.
            context.set_alpn_protocols(["h2"])
            sock = context.wrap_socket(sock, server_hostname="localhost")
            if sock.selected_alpn_protocol() != "h2":
                raise RuntimeError(f"ALPN selected {sock.selected_alpn_protocol()!r}")
        return sock


class FrameTrace:
    """Bounded record of frame headers in one direction, for failure reports."""

    NAMES = {0: "DATA", 1: "HEADERS", 2: "PRIORITY", 3: "RST_STREAM", 4: "SETTINGS", 5: "PUSH_PROMISE",
             6: "PING", 7: "GOAWAY", 8: "WINDOW_UPDATE", 9: "CONTINUATION", 16: "PRIORITY_UPDATE"}

    def __init__(self, direction, log, skip=0):
        self.direction, self.log, self.skip, self.buffer = direction, log, skip, b""
        self.started = time.monotonic()

    def feed(self, data):
        if self.skip:
            taken = min(self.skip, len(data))
            data, self.skip = data[taken:], self.skip - taken
        self.buffer += data
        while len(self.buffer) >= 9 and len(self.buffer) >= 9 + int.from_bytes(self.buffer[:3], "big"):
            length = int.from_bytes(self.buffer[:3], "big")
            kind, flags = self.buffer[3], self.buffer[4]
            stream = int.from_bytes(self.buffer[5:9], "big") & 0x7FFFFFFF
            payload = self.buffer[9:9 + length]
            detail = ""
            if kind == 4 and not flags & 1:
                detail = " " + ",".join(f"{int.from_bytes(payload[i:i + 2], 'big')}={int.from_bytes(payload[i + 2:i + 6], 'big')}"
                                        for i in range(0, len(payload) - 5, 6))
            elif kind == 8:
                detail = f" +{int.from_bytes(payload[:4], 'big') & 0x7FFFFFFF}"
            elif kind in (3, 7):
                detail = f" code={int.from_bytes(payload[-4:], 'big')}"
            self.log.append(f"{time.monotonic() - self.started:8.4f} {self.direction} {self.NAMES.get(kind, kind)} "
                            f"s={stream} f=0x{flags:02x} len={length}{detail}")
            del self.log[:-400]
            self.buffer = self.buffer[9 + length:]


class Client:
    """Single-threaded hyper-h2 client with explicit flow-controlled uploads."""

    def __init__(self, endpoint, settings=None, timeout=10.0):
        self.endpoint = endpoint
        self.sock = endpoint.connect()
        self.timeout = timeout
        self.conn = h2.connection.H2Connection(config=h2.config.H2Configuration(client_side=True, header_encoding=None))
        self.conn.initiate_connection()
        if settings:
            self.conn.update_settings(settings)
        self.streams = {}
        self.terminated = None
        self.closed = False
        self.trace = []
        self.sent_trace = FrameTrace("->", self.trace, skip=len(PREFACE))
        self.received_trace = FrameTrace("<-", self.trace)
        self.flush()

    def flush(self):
        data = self.conn.data_to_send()
        if data:
            self.sent_trace.feed(data)
            self.sock.sendall(data)

    def request(self, method, path, body=b"", headers=(), end=True):
        stream_id = self.conn.get_next_available_stream_id()
        header_list = [(b":method", method), (b":scheme", b"https" if self.endpoint.tls else b"http"),
                       (b":authority", self.endpoint.authority), (b":path", path)] + list(headers)
        if body:
            header_list.append((b"content-length", str(len(body)).encode()))
        self.conn.send_headers(stream_id, header_list, end_stream=not body and end)
        self.streams[stream_id] = {"status": None, "headers": [], "body": bytearray(), "ended": False, "reset": None,
                                   "pending": bytes(body), "end": end, "informational": []}
        self.pump_uploads()
        self.flush()
        return stream_id

    def pump_uploads(self):
        for stream_id, state in self.streams.items():
            while state["pending"] and state["reset"] is None and not state["ended"]:
                try:
                    window = self.conn.local_flow_control_window(stream_id)
                except h2.exceptions.StreamClosedError:
                    state["pending"] = b""
                    break
                size = min(window, self.conn.max_outbound_frame_size, len(state["pending"]))
                if size <= 0:
                    break
                chunk, state["pending"] = state["pending"][:size], state["pending"][size:]
                self.conn.send_data(stream_id, chunk, end_stream=not state["pending"] and state["end"])

    def reset(self, stream_id, code=8):
        self.conn.reset_stream(stream_id, error_code=code)
        self.streams[stream_id]["reset"] = ("client", code)
        self.streams[stream_id]["pending"] = b""
        self.flush()

    def receive(self, wait):
        if self.closed:
            return False
        ready, _, _ = select.select([self.sock], [], [], wait)
        if not ready:
            return True
        try:
            data = self.sock.recv(65536)
        except (ConnectionResetError, ssl.SSLError, OSError):
            data = b""
        if not data:
            self.closed = True
            return False
        self.received_trace.feed(data)
        for event in self.conn.receive_data(data):
            self.handle(event)
        self.pump_uploads()
        self.flush()
        return True

    def handle(self, event):
        if isinstance(event, h2.events.ResponseReceived):
            state = self.streams[event.stream_id]
            state["headers"] = event.headers
            state["status"] = int(dict(event.headers)[b":status"])
        elif isinstance(event, h2.events.InformationalResponseReceived):
            self.streams[event.stream_id]["informational"].append(int(dict(event.headers)[b":status"]))
        elif isinstance(event, h2.events.DataReceived):
            self.streams[event.stream_id]["body"].extend(event.data)
            if event.flow_controlled_length:
                self.conn.acknowledge_received_data(event.flow_controlled_length, event.stream_id)
        elif isinstance(event, h2.events.StreamEnded):
            self.streams[event.stream_id]["ended"] = True
        elif isinstance(event, h2.events.StreamReset):
            if event.stream_id in self.streams and self.streams[event.stream_id]["reset"] is None:
                self.streams[event.stream_id]["reset"] = ("server", event.error_code)
        elif isinstance(event, h2.events.ConnectionTerminated):
            self.terminated = (int(event.error_code), event.last_stream_id, event.additional_data)

    def done(self, stream_id):
        state = self.streams[stream_id]
        return state["ended"] or state["reset"] is not None

    def wait(self, stream_ids, timeout=None):
        deadline = time.monotonic() + (timeout or self.timeout)
        while not all(self.done(s) for s in stream_ids):
            if time.monotonic() > deadline:
                raise TimeoutError(f"streams {[s for s in stream_ids if not self.done(s)]} incomplete")
            if not self.receive(0.05) and not all(self.done(s) for s in stream_ids):
                raise ConnectionError(f"connection closed; terminated={self.terminated}")

    def header(self, stream_id, name):
        for key, value in self.streams[stream_id]["headers"]:
            if key == name:
                return value
        return None

    def close(self):
        try:
            self.conn.close_connection()
            self.flush()
        except (OSError, h2.exceptions.ProtocolError):
            pass
        self.sock.close()


def raw_frames(sock, timeout):
    """Reads raw server frames until close or timeout; returns (frames, closed)."""
    buffer = b""
    frames = []
    deadline = time.monotonic() + timeout
    closed = False
    while time.monotonic() < deadline:
        ready, _, _ = select.select([sock], [], [], max(0.0, deadline - time.monotonic()))
        if not ready:
            break
        try:
            data = sock.recv(65536)
        except (ConnectionResetError, ssl.SSLError, OSError):
            data = b""
        if not data:
            closed = True
            break
        buffer += data
        while len(buffer) >= 9:
            length = int.from_bytes(buffer[:3], "big")
            if len(buffer) < 9 + length:
                break
            frame, _ = hf.Frame.parse_frame_header(memoryview(buffer[:9]))
            frame.parse_body(memoryview(buffer[9:9 + length]))
            frames.append(frame)
            buffer = buffer[9 + length:]
        if any(isinstance(f, hf.GoAwayFrame) for f in frames):
            # Drain briefly so closure after GOAWAY is observed.
            deadline = min(deadline, time.monotonic() + 1.0)
    return frames, closed


def raw_connection(endpoint):
    sock = endpoint.connect()
    sock.sendall(PREFACE + hf.SettingsFrame(0).serialize())
    return sock


def raw_headers_block(endpoint, path=b"/plain", method=b"GET"):
    import hpack
    encoder = hpack.Encoder()
    return encoder.encode([(b":method", method), (b":scheme", b"https" if endpoint.tls else b"http"),
                           (b":authority", endpoint.authority), (b":path", path)])


def goaway_code(frames):
    for f in frames:
        if isinstance(f, hf.GoAwayFrame):
            return f.error_code
    return None


def rst_codes(frames, stream_id=None):
    return [f.error_code for f in frames if isinstance(f, hf.RstStreamFrame) and (stream_id is None or f.stream_id == stream_id)]


def healthy(endpoint):
    try:
        client = Client(endpoint)
        stream_id = client.request(b"GET", b"/plain")
        client.wait([stream_id], 5)
        ok = client.streams[stream_id]["status"] == 200 and bytes(client.streams[stream_id]["body"]) == b"hello"
        client.close()
        return None if ok else f"status {client.streams[stream_id]['status']}"
    except Exception as error:  # Driver records every failure as evidence.
        return f"{type(error).__name__}: {error}"


def stats(host, port):
    try:
        return _stats(host, port)
    except OSError as error:  # A stopped listener is itself a recorded outcome.
        return {"error": f"{type(error).__name__}: {error}", "activeHandlers": 0, "handles": 0, "managedBytes": 0}


def _stats(host, port):
    """Reads /__stats over a cleartext HTTP/1.1 port with a minimal request."""
    with socket.create_connection((host, port), timeout=10) as sock:
        sock.sendall(f"GET /__stats HTTP/1.1\r\nHost: {host}:{port}\r\nConnection: close\r\n\r\n".encode())
        data = b""
        while True:
            chunk = sock.recv(65536)
            if not chunk:
                break
            data += chunk
    head, _, body = data.partition(b"\r\n\r\n")
    if b"transfer-encoding: chunked" in head.lower():
        decoded = b""
        while body:
            size_line, _, rest = body.partition(b"\r\n")
            size = int(size_line.split(b";")[0], 16)
            if size == 0:
                break
            decoded += rest[:size]
            body = rest[size + 2:]
        body = decoded
    return json.loads(body)


# ---------------------------------------------------------------- cases

def case(cases, identifier, reference, level):
    def register(function):
        cases.append((identifier, reference, level, function))
        return function
    return register


CASES = []
ONLY = None


@case(CASES, "multiplexed-echo", "RFC9113 5; 6.9", "MUST")
def _(e):
    client = Client(e)
    rng = random.Random(7)
    expected = {}
    for _ in range(24):
        body = rng.randbytes(rng.choice([0, 1, 1000, 16384, 65535, 65536, 200_000]))
        sid = client.request(b"POST", b"/echo", body, [(b"content-type", b"application/octet-stream")])
        expected[sid] = body
    client.wait(list(expected), 30)
    bad = [s for s, b in expected.items() if bytes(client.streams[s]["body"]) != b or client.streams[s]["status"] != 200]
    client.close()
    return ("conforms" if not bad else "violation", f"{len(expected)} streams; mismatched {bad}")


@case(CASES, "small-client-window", "RFC9113 6.9.2", "MUST")
def _(e):
    # Initial window 1 byte: the server must respect it and resume after WINDOW_UPDATE.
    client = Client(e, settings={h2.settings.SettingCodes.INITIAL_WINDOW_SIZE: 1})
    sid = client.request(b"GET", b"/stream?n=50000&chunk=7000")
    client.wait([sid], 30)
    body = bytes(client.streams[sid]["body"])
    client.close()
    return ("conforms" if body == bytes(i & 0xFF for i in range(50000)) else "violation", f"{len(body)} bytes")


@case(CASES, "client-reset-upload", "RFC9113 6.4", "MUST")
def _(e):
    client = Client(e)
    sid = client.request(b"POST", b"/echo", b"x" * 300_000, end=True)
    client.receive(0.05)
    client.reset(sid)
    follow = client.request(b"GET", b"/plain")
    client.wait([follow], 10)
    ok = bytes(client.streams[follow]["body"]) == b"hello"
    client.close()
    return ("conforms" if ok else "violation", "follow-up stream served" if ok else "follow-up failed")


@case(CASES, "client-reset-download", "RFC9113 6.4", "MUST")
def _(e):
    client = Client(e)
    sid = client.request(b"GET", b"/stream?n=8000000&chunk=16000")
    client.receive(0.2)
    client.reset(sid)
    follow = client.request(b"GET", b"/plain")
    client.wait([follow], 10)
    ok = bytes(client.streams[follow]["body"]) == b"hello"
    client.close()
    return ("conforms" if ok else "violation", "follow-up stream served" if ok else "follow-up failed")


@case(CASES, "range-query-gzip", "RFC9110 14; RFC10008; RFC9110 12.5.3", "MUST")
def _(e):
    client = Client(e)
    data = file_bytes()
    r = client.request(b"GET", b"/files/data.bin", headers=[(b"range", b"bytes=100-199")])
    q = client.request(b"QUERY", b"/query", b"q=1", [(b"content-type", b"text/plain")])
    g = client.request(b"GET", b"/files/text.txt", headers=[(b"accept-encoding", b"gzip")])
    client.wait([r, q, g], 10)
    import gzip
    problems = []
    if client.streams[r]["status"] != 206 or bytes(client.streams[r]["body"]) != data[100:200]:
        problems.append(f"range {client.streams[r]['status']}")
    if bytes(client.streams[q]["body"]) != b"q=1":
        problems.append(f"query {client.streams[q]['status']}")
    body = bytes(client.streams[g]["body"])
    if client.header(g, b"content-encoding") == b"gzip":
        body = gzip.decompress(body)
    if len(body) != 2000 * 23:
        problems.append("gzip length")
    client.close()
    return ("conforms" if not problems else "violation", "; ".join(problems) or "ok")


@case(CASES, "expect-continue", "RFC9110 10.1.1; RFC9113 8.1", "SHOULD")
def _(e):
    client = Client(e)
    sid = client.request(b"POST", b"/echo", b"", [(b"expect", b"100-continue"), (b"content-length", b"3")], end=False)
    deadline = time.monotonic() + 2
    while not client.streams[sid]["informational"] and time.monotonic() < deadline:
        client.receive(0.05)
    client.conn.send_data(sid, b"abc", end_stream=True)
    client.flush()
    client.wait([sid], 5)
    detail = f"interim={client.streams[sid]['informational']} body={bytes(client.streams[sid]['body'])!r}"
    client.close()
    return ("conforms" if bytes(client.streams[sid]["body"]) == b"abc" else "violation", detail)


@case(CASES, "settings-shrink-ordering", "RFC9113 6.5.3; 6.9.2", "MUST")
def _(e):
    # Independent window accounting with raw frames: once the server ACKs a smaller
    # SETTINGS_INITIAL_WINDOW_SIZE, its later DATA must fit the adjusted window.
    worst = 0
    trials = 40
    for trial in range(trials):
        sock = raw_connection(e)
        h = hf.HeadersFrame(1, raw_headers_block(e, b"/stream?n=4000000&chunk=16000"))
        h.flags.add("END_HEADERS")
        h.flags.add("END_STREAM")
        # Large connection window so only the stream window governs.
        sock.sendall(h.serialize() + hf.WindowUpdateFrame(0, window_increment=1 << 30).serialize())
        window = 65535
        acked = False
        acks = 0  # ACKs arrive in SETTINGS order; the second answers the shrink.
        sent_shrink = False
        new_size = [0, 1, 1000, 8000][trial % 4]
        buffer = b""
        deadline = time.monotonic() + 3
        while time.monotonic() < deadline:
            ready, _, _ = select.select([sock], [], [], 0.2)
            if not ready:
                if acked:
                    break
                continue
            data = sock.recv(65536)
            if not data:
                break
            buffer += data
            while len(buffer) >= 9 and len(buffer) >= 9 + int.from_bytes(buffer[:3], "big"):
                length = int.from_bytes(buffer[:3], "big")
                frame_type, flags = buffer[3], buffer[4]
                buffer = buffer[9 + length:]
                if frame_type == 0x0:
                    window -= length
                    if acked and window < worst:
                        worst = window
                    if not sent_shrink and window < 65535 - 16000 * (trial % 3):
                        sock.sendall(hf.SettingsFrame(0, settings={4: new_size}).serialize())
                        sent_shrink = True
                elif frame_type == 0x4 and flags & 1:
                    acks += 1
                    if acks == 2:
                        acked = True
                        window += new_size - 65535
        sock.close()
    return ("conforms" if worst >= 0 else "violation",
            f"{trials} trials; most negative stream window observed after SETTINGS ACK: {worst}")


@case(CASES, "settings-pair-ordering", "RFC9113 6.5.3; 6.9.2", "MUST")
def _(e):
    # Close the stream window with one SETTINGS, reopen it with a second. DATA the
    # server writes between the two ACKs exceeds the window the client has applied.
    violations = 0
    worst = 0
    trials = 60
    for trial in range(trials):
        sock = raw_connection(e)
        h = hf.HeadersFrame(1, raw_headers_block(e, b"/stream?n=4000000&chunk=16000"))
        h.flags.add("END_HEADERS")
        h.flags.add("END_STREAM")
        sock.sendall(h.serialize() + hf.WindowUpdateFrame(0, window_increment=1 << 30).serialize())
        window = 65535
        acks = 0
        sent = False
        trigger = [0, 16384, 40000][trial % 3]
        buffer = b""
        overrun = False
        deadline = time.monotonic() + 3
        while time.monotonic() < deadline and acks < 3:
            ready, _, _ = select.select([sock], [], [], 0.2)
            if not ready:
                continue
            data = sock.recv(65536)
            if not data:
                break
            buffer += data
            while len(buffer) >= 9 and len(buffer) >= 9 + int.from_bytes(buffer[:3], "big"):
                length = int.from_bytes(buffer[:3], "big")
                frame_type, flags = buffer[3], buffer[4]
                buffer = buffer[9 + length:]
                if frame_type == 0x0:
                    window -= length
                    if window < 0:
                        overrun = True
                        worst = min(worst, window)
                    if not sent and 65535 - window >= trigger:
                        sock.sendall(hf.SettingsFrame(0, settings={4: 0}).serialize() + hf.SettingsFrame(0, settings={4: 65535}).serialize())
                        sent = True
                elif frame_type == 0x4 and flags & 1:
                    acks += 1
                    if acks == 2:
                        window -= 65535  # Applied: INITIAL_WINDOW_SIZE 65535 -> 0.
                    elif acks == 3:
                        window += 65535  # Applied: 0 -> 65535.
        violations += overrun
        sock.close()
    return ("conforms" if violations == 0 else "violation",
            f"{violations} of {trials} trials received DATA beyond the acknowledged window (worst {worst})")


@case(CASES, "reset-while-responding", "RFC9113 5.4.2; 6.4", "MUST")
def _(e):
    # Minimized from h2 fuzz seed 20261009: RST_STREAM on a request whose response may be
    # in progress is a stream-level event; the connection must survive and answer PING.
    import hpack
    rng = random.Random(1309)
    dropped = []
    trials = 300
    for trial in range(trials):
        sock = raw_connection(e)
        encoder = hpack.Encoder()
        path = rng.choice([b"/plain", b"/stream?n=100000&chunk=700", b"/files/data.bin", b"/slow?ms=5"])
        first = hf.HeadersFrame(1, encoder.encode([(b":method", b"GET"), (b":scheme", b"http"), (b":authority", e.authority), (b":path", path)]))
        first.flags.add("END_HEADERS")
        first.flags.add("END_STREAM")
        second = hf.HeadersFrame(3, encoder.encode([(b":method", b"POST"), (b":scheme", b"http"), (b":authority", e.authority),
                                                    (b":path", b"/echo"), (b"content-length", b"100")]))
        second.flags.add("END_HEADERS")
        body = hf.DataFrame(3, b"b" * 100)
        body.flags.add("END_STREAM")
        sock.sendall(first.serialize() + second.serialize() + body.serialize())
        time.sleep(rng.choice([0, 0, 0.0005, 0.001, 0.003]))
        code = rng.choice([0, 8])
        try:
            sock.sendall(hf.RstStreamFrame(1, code).serialize() + hf.PingFrame(0, opaque_data=b"embedio!").serialize())
        except OSError:
            dropped.append((trial, path.decode(), code, "send failed"))
            sock.close()
            continue
        frames, closed = raw_frames(sock, 1.5)
        acked = any(isinstance(f, hf.PingFrame) and "ACK" in f.flags for f in frames)
        if not acked:
            dropped.append((trial, path.decode(), code, f"closed={closed} goaway={goaway_code(frames)}"))
        sock.close()
    return ("conforms" if not dropped else "violation",
            f"{len(dropped)} of {trials} connections lost after RST_STREAM; first: {dropped[:5]}")


@case(CASES, "client-goaway-drains", "RFC9113 6.8", "MUST")
def _(e):
    client = Client(e)
    sid = client.request(b"GET", b"/slow?ms=300")
    # Raw GOAWAY: h2 would otherwise refuse the server frames that legitimately follow.
    # Last-Stream-ID 0 refers to server-initiated streams; the request stays in flight.
    client.sock.sendall(hf.GoAwayFrame(0, last_stream_id=0, error_code=0).serialize())
    client.wait([sid], 10)
    ok = bytes(client.streams[sid]["body"]) == b"slow"
    client.sock.close()
    return ("conforms" if ok else "policy", f"in-flight stream after client GOAWAY: {client.streams[sid]['status']}")


@case(CASES, "max-concurrent-streams", "RFC9113 5.1.2", "MUST")
def _(e):
    client = Client(e)
    client.receive(0.3)
    limit = client.conn.remote_settings.max_concurrent_streams
    if limit is None or limit > 2000:
        client.close()
        return ("policy", f"server advertises MAX_CONCURRENT_STREAMS={limit}")
    # h2 refuses to exceed the limit, so exceed it with raw frames on a fresh connection.
    client.close()
    sock = raw_connection(e)
    block = raw_headers_block(e, b"/slow?ms=2000")
    frames = b""
    for i in range(limit + 5):
        f = hf.HeadersFrame(1 + 2 * i, block)
        f.flags.add("END_HEADERS")
        f.flags.add("END_STREAM")
        frames += f.serialize()
    sock.sendall(frames)
    got, closed = raw_frames(sock, 4)
    sock.close()
    refused = rst_codes(got).count(7) + rst_codes(got).count(1)
    goaway = goaway_code(got)
    ok = refused >= 5 or goaway == 1
    return ("conforms" if ok else "violation", f"limit={limit}; RST codes={sorted(set(rst_codes(got)))}; GOAWAY={goaway}; closed={closed}")


@case(CASES, "rapid-reset", "RFC9113 10.5; CVE-2023-44487", "SHOULD")
def _(e):
    sock = raw_connection(e)
    block = raw_headers_block(e, b"/slow?ms=1000")
    payload = b""
    for i in range(5000):
        h = hf.HeadersFrame(1 + 2 * i, block)
        h.flags.add("END_HEADERS")
        h.flags.add("END_STREAM")
        payload += h.serialize() + hf.RstStreamFrame(1 + 2 * i, 8).serialize()
    started = time.monotonic()
    try:
        sock.sendall(payload)
    except OSError:
        pass
    got, closed = raw_frames(sock, 5)
    sock.close()
    code = goaway_code(got)
    return ("policy", f"5000 open+reset pairs in {time.monotonic() - started:.2f}s; GOAWAY={ERROR_NAMES.get(code, code)}; closed={closed}")


@case(CASES, "continuation-flood", "RFC9113 6.10; 10.5", "SHOULD")
def _(e):
    sock = raw_connection(e)
    h = hf.HeadersFrame(1, raw_headers_block(e))
    sock.sendall(h.serialize())
    sent = 0
    filler = hf.ContinuationFrame(1, b"\x40\x01a\x01b" * 2000).serialize()
    started = time.monotonic()
    try:
        while time.monotonic() - started < 3:
            sock.sendall(filler)
            sent += len(filler)
    except OSError:
        pass
    got, closed = raw_frames(sock, 3)
    sock.close()
    code = goaway_code(got)
    ok = closed or code is not None
    return ("conforms" if ok else "violation", f"sent {sent} CONTINUATION bytes; GOAWAY={ERROR_NAMES.get(code, code)}; closed={closed}")


@case(CASES, "ping-flood", "RFC9113 10.5; CVE-2019-9512", "SHOULD")
def _(e):
    sock = raw_connection(e)
    pings = b"".join(hf.PingFrame(0, opaque_data=struct.pack(">Q", i)).serialize() for i in range(20000))
    try:
        sock.sendall(pings)
    except OSError:
        pass
    got, closed = raw_frames(sock, 3)
    sock.close()
    acks = sum(1 for f in got if isinstance(f, hf.PingFrame) and "ACK" in f.flags)
    return ("policy", f"20000 PINGs: {acks} ACKs; GOAWAY={ERROR_NAMES.get(goaway_code(got))}; closed={closed}")


@case(CASES, "settings-flood", "RFC9113 10.5; CVE-2019-9515", "SHOULD")
def _(e):
    sock = raw_connection(e)
    settings = b"".join(hf.SettingsFrame(0, settings={4: 65535 + (i % 7)}).serialize() for i in range(20000))
    try:
        sock.sendall(settings)
    except OSError:
        pass
    got, closed = raw_frames(sock, 3)
    sock.close()
    acks = sum(1 for f in got if isinstance(f, hf.SettingsFrame) and "ACK" in f.flags)
    return ("policy", f"20000 SETTINGS: {acks} ACKs; GOAWAY={ERROR_NAMES.get(goaway_code(got))}; closed={closed}")


@case(CASES, "empty-data-flood", "RFC9113 10.5; CVE-2019-9518", "SHOULD")
def _(e):
    sock = raw_connection(e)
    h = hf.HeadersFrame(1, raw_headers_block(e, b"/echo", b"POST"))
    h.flags.add("END_HEADERS")
    frames = h.serialize() + hf.DataFrame(1, b"").serialize() * 50000
    try:
        sock.sendall(frames)
    except OSError:
        pass
    got, closed = raw_frames(sock, 3)
    sock.close()
    return ("policy", f"50000 empty DATA: GOAWAY={ERROR_NAMES.get(goaway_code(got))}; RST={sorted(set(rst_codes(got)))}; closed={closed}")


@case(CASES, "zero-window-hold", "RFC9113 6.9; CVE-2019-9517", "SHOULD")
def _(e):
    # The client never opens its window; the server must not buffer unboundedly or hang shutdown.
    client = Client(e, settings={h2.settings.SettingCodes.INITIAL_WINDOW_SIZE: 0})
    sids = [client.request(b"GET", b"/stream?n=4000000&chunk=65536") for _ in range(8)]
    deadline = time.monotonic() + 3
    while time.monotonic() < deadline:
        client.receive(0.1)
    received = sum(len(client.streams[s]["body"]) for s in sids)
    client.sock.close()
    return ("policy", f"8 blocked 4MB streams; {received} bytes delivered with zero window (expected 0)")


@case(CASES, "invalid-pseudo-header", "RFC9113 8.3", "MUST")
def _(e):
    import hpack
    sock = raw_connection(e)
    block = hpack.Encoder().encode([(b":method", b"GET"), (b":scheme", b"http"), (b":path", b"/plain"),
                                    (b":authority", e.authority), (b":bogus", b"x")])
    h = hf.HeadersFrame(1, block)
    h.flags.add("END_HEADERS")
    h.flags.add("END_STREAM")
    sock.sendall(h.serialize())
    got, closed = raw_frames(sock, 2)
    sock.close()
    rst = rst_codes(got, 1)
    ok = 1 in rst or goaway_code(got) == 1
    return ("conforms" if ok else "violation", f"RST={rst}; GOAWAY={goaway_code(got)}")


@case(CASES, "uppercase-field-name", "RFC9113 8.2.1", "MUST")
def _(e):
    import hpack
    sock = raw_connection(e)
    block = hpack.Encoder().encode([(b":method", b"GET"), (b":scheme", b"http"), (b":path", b"/plain"),
                                    (b":authority", e.authority), (b"X-Upper", b"x")])
    h = hf.HeadersFrame(1, block)
    h.flags.add("END_HEADERS")
    h.flags.add("END_STREAM")
    sock.sendall(h.serialize())
    got, closed = raw_frames(sock, 2)
    sock.close()
    rst = rst_codes(got, 1)
    ok = 1 in rst or goaway_code(got) == 1
    return ("conforms" if ok else "violation", f"RST={rst}; GOAWAY={goaway_code(got)}")


@case(CASES, "connection-specific-field", "RFC9113 8.2.2", "MUST")
def _(e):
    import hpack
    sock = raw_connection(e)
    block = hpack.Encoder().encode([(b":method", b"GET"), (b":scheme", b"http"), (b":path", b"/plain"),
                                    (b":authority", e.authority), (b"connection", b"keep-alive")])
    h = hf.HeadersFrame(1, block)
    h.flags.add("END_HEADERS")
    h.flags.add("END_STREAM")
    sock.sendall(h.serialize())
    got, closed = raw_frames(sock, 2)
    sock.close()
    rst = rst_codes(got, 1)
    ok = 1 in rst or goaway_code(got) == 1
    return ("conforms" if ok else "violation", f"RST={rst}; GOAWAY={goaway_code(got)}")


@case(CASES, "options-asterisk", "RFC9113 8.3.1", "MUST")
def _(e):
    client = Client(e)
    sid = client.request(b"OPTIONS", b"*")
    client.wait([sid], 5)
    status = client.streams[sid]["status"]
    client.close()
    return ("policy", f"OPTIONS * -> {status}")


@case(CASES, "content-length-mismatch", "RFC9113 8.1.1", "MUST")
def _(e):
    sock = raw_connection(e)
    import hpack
    block = hpack.Encoder().encode([(b":method", b"POST"), (b":scheme", b"http"), (b":path", b"/echo"),
                                    (b":authority", e.authority), (b"content-length", b"10")])
    h = hf.HeadersFrame(1, block)
    h.flags.add("END_HEADERS")
    d = hf.DataFrame(1, b"abc")
    d.flags.add("END_STREAM")
    sock.sendall(h.serialize() + d.serialize())
    got, closed = raw_frames(sock, 2)
    sock.close()
    rst = rst_codes(got, 1)
    statuses = [f for f in got if isinstance(f, hf.HeadersFrame) and f.stream_id == 1]
    ok = 1 in rst or goaway_code(got) == 1
    return ("conforms" if ok else "violation", f"RST={rst}; GOAWAY={goaway_code(got)}; response HEADERS frames={len(statuses)}")


def run_cases(endpoint, stats_port):
    results = []
    before = stats(endpoint.host, stats_port) if stats_port else None
    for identifier, reference, level, function in CASES:
        if ONLY and ONLY not in identifier:
            continue
        started = time.monotonic()
        try:
            result, detail = function(endpoint)
        except Exception as error:  # Recorded as an error outcome.
            result, detail = "error", f"{type(error).__name__}: {error}"
        health = healthy(endpoint)
        if health:
            result, detail = "violation", f"{detail}; UNHEALTHY AFTER CASE: {health}"
        results.append({"id": identifier, "reference": reference, "level": level, "result": result,
                        "detail": detail, "seconds": round(time.monotonic() - started, 3)})
        print(f"{result:<10} {identifier:<28} {level:<7} {reference:<32} {detail}", flush=True)
    after = settle(endpoint, stats_port) if stats_port else None
    return {"outcomes": results, "stats_before": before, "stats_after": after}


def settle(endpoint, stats_port):
    snapshot = stats(endpoint.host, stats_port)
    for _ in range(50):
        if snapshot["activeHandlers"] == 0:
            break
        time.sleep(0.1)
        snapshot = stats(endpoint.host, stats_port)
    return snapshot


# ---------------------------------------------------------------- campaign

def run_fuzz(endpoint, seed, iterations, stats_port):
    """Random interleavings of opens, uploads, resets, window and settings changes."""
    rng = random.Random(seed)
    data = file_bytes()
    before = stats(endpoint.host, stats_port) if stats_port else None
    totals = {"streams": 0, "client_resets": 0, "server_resets": 0, "connections": 0}
    for iteration in range(iterations):
        log = []
        settings = {}
        if rng.random() < 0.3:
            settings[h2.settings.SettingCodes.INITIAL_WINDOW_SIZE] = rng.choice([0, 1, 100, 16384, 65535, 1 << 20])
        if rng.random() < 0.2:
            settings[h2.settings.SettingCodes.HEADER_TABLE_SIZE] = rng.choice([0, 64, 4096])
        if rng.random() < 0.2:
            settings[h2.settings.SettingCodes.MAX_FRAME_SIZE] = rng.choice([16384, 32768, 1 << 20])
        try:
            client = Client(endpoint, settings=settings or None)
            totals["connections"] += 1
            expected = {}
            for _ in range(rng.randint(1, 12)):
                action = rng.random()
                if action < 0.55 or not expected:
                    kind = rng.random()
                    if kind < 0.4:
                        body = rng.randbytes(rng.choice([0, 1, 100, 5000, 70000, 300000]))
                        sid = client.request(rng.choice([b"POST", b"PUT", b"QUERY"]) if body else b"POST",
                                             b"/echo", body, [(b"content-type", b"application/octet-stream")])
                        expected[sid] = ("echo", body)
                    elif kind < 0.6:
                        start = rng.randrange(FILE_LENGTH)
                        end = min(FILE_LENGTH - 1, start + rng.randrange(20000))
                        sid = client.request(b"GET", b"/files/data.bin", headers=[(b"range", f"bytes={start}-{end}".encode())])
                        expected[sid] = ("range", data[start:end + 1])
                    elif kind < 0.8:
                        n = rng.choice([0, 1, 16384, 100000])
                        sid = client.request(b"GET", f"/stream?n={n}&chunk={rng.choice([1, 700, 16384])}".encode())
                        expected[sid] = ("stream", bytes(i & 0xFF for i in range(n)))
                    else:
                        sid = client.request(rng.choice([b"GET", b"HEAD"]), b"/plain", headers=[(b"x-r", str(rng.random()).encode())] * rng.randint(0, 5))
                        expected[sid] = ("plain", None)
                    log.append(("open", sid))
                elif action < 0.7:
                    sid = rng.choice(list(expected))
                    if not client.done(sid):
                        client.reset(sid, rng.choice([0, 8, 2]))
                        totals["client_resets"] += 1
                        log.append(("reset", sid))
                elif action < 0.8:
                    client.conn.ping(rng.randbytes(8))
                    client.flush()
                    log.append(("ping",))
                elif action < 0.9:
                    client.conn.increment_flow_control_window(rng.randint(1, 1 << 20))
                    client.flush()
                    log.append(("window",))
                else:
                    client.conn.update_settings({h2.settings.SettingCodes.INITIAL_WINDOW_SIZE: rng.choice([0, 1000, 65535, 1 << 20])})
                    client.flush()
                    log.append(("settings",))
                for _ in range(rng.randint(0, 3)):
                    client.receive(0.01)
            # Any window left at zero is reopened so every live stream can complete.
            client.conn.update_settings({h2.settings.SettingCodes.INITIAL_WINDOW_SIZE: 65535})
            client.conn.increment_flow_control_window(1 << 24)
            client.flush()
            client.wait(list(expected), 30)
            for sid, (kind, body) in expected.items():
                state = client.streams[sid]
                totals["streams"] += 1
                if state["reset"] is not None:
                    if state["reset"][0] == "server":
                        totals["server_resets"] += 1
                        if state["reset"][1] not in (7, 8, 0):
                            raise AssertionError(f"stream {sid} reset by server with {ERROR_NAMES.get(state['reset'][1])}")
                    continue
                if kind == "plain":
                    if state["status"] != 200:
                        raise AssertionError(f"stream {sid} plain status {state['status']}")
                    continue
                if kind == "range" and state["status"] != 206:
                    raise AssertionError(f"stream {sid} range status {state['status']}")
                if bytes(state["body"]) != body:
                    raise AssertionError(f"stream {sid} {kind}: {len(state['body'])} of {len(body)} bytes; status {state['status']}")
            if client.terminated:
                raise AssertionError(f"server terminated a valid connection: {client.terminated}")
            client.close()
        except (BrokenPipeError, ConnectionResetError, ConnectionError) as error:
            return {"result": "FAIL", "seed": seed, "iteration": iteration, "error": f"{type(error).__name__}: {error}", "log": log,
                    "trace": client.trace if "client" in locals() else []}
        except Exception as error:  # A failed invariant is a finding with a replayable seed.
            return {"result": "FAIL", "seed": seed, "iteration": iteration, "settings": {int(k): v for k, v in settings.items()},
                    "error": f"{type(error).__name__}: {error}", "log": log,
                    "trace": client.trace if "client" in locals() else []}
        if (iteration + 1) % max(1, iterations // 5) == 0:
            health = healthy(endpoint)
            if health:
                return {"result": "FAIL", "seed": seed, "iteration": iteration, "error": "unhealthy: " + health}
    after = settle(endpoint, stats_port) if stats_port else None
    report = {"result": "PASS", "seed": seed, "iterations": iterations, "totals": totals,
              "stats_before": before, "stats_after": after}
    if before and after:
        report["handleGrowth"] = after["handles"] - before["handles"]
        report["managedGrowth"] = after["managedBytes"] - before["managedBytes"]
        if after["activeHandlers"] or report["handleGrowth"] > 64 or report["managedGrowth"] > 32 << 20:
            report["result"] = "FAIL"
            report["error"] = "resources did not settle"
    return report


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=["cases", "fuzz"])
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, required=True)
    parser.add_argument("--authority")
    parser.add_argument("--tls", action="store_true")
    parser.add_argument("--stats-port", type=int)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--iterations", type=int, default=200)
    parser.add_argument("--out")
    parser.add_argument("--only", help="run only cases whose id contains this text")
    args = parser.parse_args()
    global ONLY
    ONLY = args.only
    endpoint = Endpoint(args.host, args.port, args.tls, (args.authority or f"{args.host}:{args.port}").encode())
    import h2 as h2_package
    identity = {"h2": h2_package.__version__, "python": sys.version, "target": f"{args.host}:{args.port}", "tls": args.tls}
    if args.mode == "cases":
        report = run_cases(endpoint, args.stats_port)
        failed = any(o["result"] in ("violation", "error") for o in report["outcomes"])
        counts = {}
        for o in report["outcomes"]:
            counts[o["result"]] = counts.get(o["result"], 0) + 1
        print(counts)
    else:
        report = run_fuzz(endpoint, args.seed, args.iterations, args.stats_port)
        failed = report["result"] != "PASS"
        print(json.dumps(report)[:4000])
    report["identity"] = identity
    if args.out:
        with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(report, handle, indent=1, ensure_ascii=True)
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
