"""HTTP/3 conformance cases and stateful campaign (development-only).

The client is aioquic, an independent QUIC/HTTP/3/QPACK implementation. Its QPACK
decoder (ls-qpack) accepts the server's dynamic-table responses, so every response
also checks the server encoder. Bodies are verified byte for byte.

Usage:
  python -I h3_campaign.py cases --host localhost --port P [--stats-port P] [--out FILE]
  python -I h3_campaign.py fuzz  --host localhost --port P --seed S --iterations N [--out FILE]
"""

import argparse
import asyncio
import gzip
import json
import random
import socket
import ssl
import sys
import time

from aioquic.asyncio.client import connect
from aioquic.asyncio.protocol import QuicConnectionProtocol
from aioquic.h3.connection import H3_ALPN, H3Connection
from aioquic.h3.events import DataReceived, HeadersReceived
from aioquic.quic.configuration import QuicConfiguration
from aioquic.quic.events import ConnectionTerminated, StreamReset

FILE_LENGTH = 100_000
H3_REQUEST_CANCELLED = 0x10C


def file_bytes():
    return bytes((i * 31 + (i >> 8)) & 0xFF for i in range(FILE_LENGTH))


class Client(QuicConnectionProtocol):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.http = H3Connection(self._quic)
        self.streams = {}
        self.terminated = None

    def request(self, method, path, authority, body=b"", headers=()):
        stream_id = self._quic.get_next_available_stream_id()
        header_list = [(b":method", method), (b":scheme", b"https"), (b":authority", authority), (b":path", path)] + list(headers)
        if body:
            header_list.append((b"content-length", str(len(body)).encode()))
        state = {"status": None, "headers": [], "body": bytearray(), "ended": False, "reset": None, "done": asyncio.Event()}
        self.streams[stream_id] = state
        self.http.send_headers(stream_id, header_list, end_stream=not body)
        if body:
            self.http.send_data(stream_id, body, end_stream=True)
        self.transmit()
        return stream_id

    def cancel(self, stream_id):
        state = self.streams[stream_id]
        if state["done"].is_set():
            return False
        self._quic.reset_stream(stream_id, H3_REQUEST_CANCELLED)
        if hasattr(self._quic, "stop_stream"):
            self._quic.stop_stream(stream_id, H3_REQUEST_CANCELLED)
        state["reset"] = ("client", H3_REQUEST_CANCELLED)
        state["done"].set()
        self.transmit()
        return True

    def quic_event_received(self, event):
        if isinstance(event, StreamReset):
            state = self.streams.get(event.stream_id)
            if state and state["reset"] is None:
                state["reset"] = ("server", event.error_code)
                state["done"].set()
        elif isinstance(event, ConnectionTerminated):
            self.terminated = (event.error_code, event.reason_phrase)
            for state in self.streams.values():
                state["done"].set()
        for http_event in self.http.handle_event(event):
            state = self.streams.get(getattr(http_event, "stream_id", -1))
            if state is None or state["reset"] is not None:
                continue
            if isinstance(http_event, HeadersReceived):
                status = dict(http_event.headers).get(b":status")
                if status and int(status) >= 200:
                    state["status"] = int(status)
                    state["headers"] = http_event.headers
            elif isinstance(http_event, DataReceived):
                state["body"].extend(http_event.data)
            if getattr(http_event, "stream_ended", False):
                state["ended"] = True
                state["done"].set()

    def header(self, stream_id, name):
        return dict(self.streams[stream_id]["headers"]).get(name)

    async def wait(self, stream_ids, timeout=30):
        await asyncio.wait_for(asyncio.gather(*(self.streams[s]["done"].wait() for s in stream_ids)), timeout)


def configuration():
    config = QuicConfiguration(is_client=True, alpn_protocols=H3_ALPN, server_name="localhost")
    config.verify_mode = ssl.CERT_NONE  # Test certificate generated by the host.
    config.idle_timeout = 20
    return config


class Session:
    def __init__(self, host, port):
        self.host, self.port = host, port
        self.authority = f"{host}:{port}".encode()

    def open(self):
        return connect(self.host, self.port, configuration=configuration(), create_protocol=Client, wait_connected=True)


async def healthy(session):
    try:
        async with session.open() as client:
            sid = client.request(b"GET", b"/plain", session.authority)
            await client.wait([sid], 10)
            state = client.streams[sid]
            return None if state["status"] == 200 and bytes(state["body"]) == b"hello" else f"status {state['status']} reset {state['reset']}"
    except Exception as error:  # Recorded as evidence.
        return f"{type(error).__name__}: {error}"


def stats(host, port):
    try:
        return _stats(host, port)
    except OSError as error:  # A stopped listener is itself a recorded outcome.
        return {"error": f"{type(error).__name__}: {error}", "activeHandlers": 0, "handles": 0, "managedBytes": 0}


def _stats(host, port):
    with socket.create_connection((host, port), timeout=10) as sock:
        sock.sendall(f"GET /__stats HTTP/1.1\r\nHost: {host}:{port}\r\nConnection: close\r\n\r\n".encode())
        data = b""
        while chunk := sock.recv(65536):
            data += chunk
    head, _, body = data.partition(b"\r\n\r\n")
    if b"transfer-encoding: chunked" in head.lower():
        decoded = b""
        while body:
            size_line, _, rest = body.partition(b"\r\n")
            size = int(size_line.split(b";")[0], 16)
            if size == 0:
                break
            decoded += rest[:size]
            body = rest[size + 2:]
        body = decoded
    return json.loads(body)


CASES = []
ONLY = None


def case(identifier, reference, level):
    def register(function):
        CASES.append((identifier, reference, level, function))
        return function
    return register


@case("multiplexed-echo", "RFC9114 4.1; RFC9000 4", "MUST")
async def _(s):
    rng = random.Random(9)
    async with s.open() as client:
        expected = {}
        for _ in range(24):
            body = rng.randbytes(rng.choice([0, 1, 1000, 65536, 300_000]))
            sid = client.request(b"POST", b"/echo", s.authority, body, [(b"content-type", b"application/octet-stream")])
            expected[sid] = body
        await client.wait(list(expected), 60)
        bad = [sid for sid, body in expected.items() if bytes(client.streams[sid]["body"]) != body or client.streams[sid]["status"] != 200]
    return ("conforms" if not bad else "violation", f"{len(expected)} streams; mismatched {bad}")


@case("client-cancel-upload", "RFC9114 4.1.1", "MUST")
async def _(s):
    async with s.open() as client:
        sid = client.request(b"POST", b"/echo", s.authority, b"x" * 2_000_000)
        await asyncio.sleep(0.05)
        client.cancel(sid)
        follow = client.request(b"GET", b"/plain", s.authority)
        await client.wait([follow], 10)
        ok = bytes(client.streams[follow]["body"]) == b"hello"
    return ("conforms" if ok else "violation", "follow-up served" if ok else "follow-up failed")


@case("client-cancel-download", "RFC9114 4.1.1", "MUST")
async def _(s):
    async with s.open() as client:
        sid = client.request(b"GET", b"/stream?n=16000000&chunk=16000", s.authority)
        await asyncio.sleep(0.2)
        client.cancel(sid)
        follow = client.request(b"GET", b"/plain", s.authority)
        await client.wait([follow], 10)
        ok = bytes(client.streams[follow]["body"]) == b"hello"
    return ("conforms" if ok else "violation", "follow-up served" if ok else "follow-up failed")


@case("range-query-gzip", "RFC9110 14; RFC10008; RFC9110 12.5.3", "MUST")
async def _(s):
    data = file_bytes()
    async with s.open() as client:
        r = client.request(b"GET", b"/files/data.bin", s.authority, headers=[(b"range", b"bytes=100-199")])
        q = client.request(b"QUERY", b"/query", s.authority, b"q=1", [(b"content-type", b"text/plain")])
        g = client.request(b"GET", b"/files/text.txt", s.authority, headers=[(b"accept-encoding", b"gzip")])
        await client.wait([r, q, g], 10)
        problems = []
        if client.streams[r]["status"] != 206 or bytes(client.streams[r]["body"]) != data[100:200]:
            problems.append(f"range {client.streams[r]['status']}")
        if bytes(client.streams[q]["body"]) != b"q=1":
            problems.append(f"query {client.streams[q]['status']}")
        body = bytes(client.streams[g]["body"])
        if client.header(g, b"content-encoding") == b"gzip":
            body = gzip.decompress(body)
        if len(body) != 2000 * 23:
            problems.append("gzip length")
    return ("conforms" if not problems else "violation", "; ".join(problems) or "ok")


@case("qpack-repeated-headers", "RFC9204 2.1", "MUST")
async def _(s):
    # Many responses with the same fields let the server populate its dynamic table.
    async with s.open() as client:
        sids = [client.request(b"GET", b"/files/text.txt", s.authority, headers=[(b"accept-encoding", b"identity")]) for _ in range(64)]
        await client.wait(sids, 30)
        bad = [sid for sid in sids if client.streams[sid]["status"] != 200]
        decoder = getattr(client.http, "_decoder_bytes_sent", None)
    return ("conforms" if not bad else "violation", f"64 responses; failures {bad}; decoder bytes sent {decoder}")


@case("many-streams", "RFC9000 4.6; RFC9114 6.1", "MUST")
async def _(s):
    async with s.open() as client:
        sids = [client.request(b"GET", b"/plain", s.authority) for _ in range(400)]
        await client.wait(sids, 60)
        ok = sum(1 for sid in sids if bytes(client.streams[sid]["body"]) == b"hello")
        refused = sum(1 for sid in sids if client.streams[sid]["reset"])
    return ("conforms" if ok + refused == 400 and ok > 0 else "violation", f"served {ok}; reset {refused}")


@case("cancel-upload-storm", "RFC9114 4.1.1; 10.5", "MUST")
async def _(s):
    # Cancels uploads at varied points; one client's cancellation must never stop
    # the listener for everyone. Health is checked on a fresh connection each round.
    rng = random.Random(4441)
    for attempt in range(1, 201):
        async with s.open() as client:
            sids = [client.request(b"POST", b"/echo", s.authority, b"u" * rng.choice([20000, 200000, 2000000])) for _ in range(4)]
            await asyncio.sleep(rng.choice([0, 0.001, 0.005, 0.02, 0.05]))
            for sid in sids:
                client.cancel(sid)
            await asyncio.sleep(0.01)
        if attempt % 10 == 0:
            health = await healthy(s)
            if health:
                return ("violation", f"listener unusable after {attempt} cancel rounds (4 uploads each): {health}")
    return ("conforms", "200 rounds of 4 cancelled uploads; listener stayed healthy")


@case("rapid-cancel", "RFC9114 10.5", "SHOULD")
async def _(s):
    async with s.open() as client:
        started = time.monotonic()
        sids = []
        for _ in range(2000):
            sid = client.request(b"GET", b"/slow?ms=1000", s.authority)
            client.cancel(sid)
            sids.append(sid)
        await asyncio.sleep(1)
        terminated = client.terminated
    return ("policy", f"2000 open+cancel in {time.monotonic() - started:.2f}s; terminated={terminated}")


async def run_cases(session, stats_port):
    results = []
    before = stats(session.host, stats_port) if stats_port else None
    for identifier, reference, level, function in CASES:
        if ONLY and ONLY not in identifier:
            continue
        started = time.monotonic()
        try:
            result, detail = await function(session)
        except Exception as error:  # Recorded as an error outcome.
            result, detail = "error", f"{type(error).__name__}: {error}"
        health = await healthy(session)
        if health:
            result, detail = "violation", f"{detail}; UNHEALTHY AFTER CASE: {health}"
        results.append({"id": identifier, "reference": reference, "level": level, "result": result,
                        "detail": detail, "seconds": round(time.monotonic() - started, 3)})
        print(f"{result:<10} {identifier:<26} {level:<7} {reference:<30} {detail}", flush=True)
    after = await settle(session, stats_port) if stats_port else None
    return {"outcomes": results, "stats_before": before, "stats_after": after}


async def settle(session, stats_port):
    snapshot = stats(session.host, stats_port)
    for _ in range(50):
        if snapshot["activeHandlers"] == 0:
            break
        await asyncio.sleep(0.1)
        snapshot = stats(session.host, stats_port)
    return snapshot


async def run_fuzz(session, seed, iterations, stats_port):
    rng = random.Random(seed)
    data = file_bytes()
    before = stats(session.host, stats_port) if stats_port else None
    totals = {"streams": 0, "client_cancels": 0, "server_resets": 0, "connections": 0}
    for iteration in range(iterations):
        log = []
        try:
            async with session.open() as client:
                totals["connections"] += 1
                expected = {}
                for _ in range(rng.randint(1, 16)):
                    roll = rng.random()
                    if roll < 0.8 or not expected:
                        kind = rng.random()
                        if kind < 0.4:
                            body = rng.randbytes(rng.choice([0, 1, 100, 5000, 70000, 400000]))
                            sid = client.request(rng.choice([b"POST", b"PUT", b"QUERY"]), b"/echo", session.authority, body,
                                                 [(b"content-type", b"application/octet-stream")])
                            expected[sid] = ("echo", body)
                        elif kind < 0.6:
                            start = rng.randrange(FILE_LENGTH)
                            end = min(FILE_LENGTH - 1, start + rng.randrange(20000))
                            sid = client.request(b"GET", b"/files/data.bin", session.authority, headers=[(b"range", f"bytes={start}-{end}".encode())])
                            expected[sid] = ("range", data[start:end + 1])
                        elif kind < 0.8:
                            n = rng.choice([0, 1, 16384, 200000])
                            sid = client.request(b"GET", f"/stream?n={n}&chunk={rng.choice([1, 700, 16384])}".encode(), session.authority)
                            expected[sid] = ("stream", bytes(i & 0xFF for i in range(n)))
                        else:
                            sid = client.request(b"GET", b"/plain", session.authority, headers=[(b"x-r", str(rng.random()).encode())] * rng.randint(0, 6))
                            expected[sid] = ("plain", b"hello")
                        log.append(("open", sid))
                    else:
                        sid = rng.choice(list(expected))
                        if client.cancel(sid):
                            totals["client_cancels"] += 1
                            log.append(("cancel", sid))
                    if rng.random() < 0.3:
                        await asyncio.sleep(rng.choice([0, 0.001, 0.01]))
                await client.wait(list(expected), 60)
                for sid, (kind, body) in expected.items():
                    state = client.streams[sid]
                    totals["streams"] += 1
                    if state["reset"] is not None:
                        if state["reset"][0] == "server":
                            totals["server_resets"] += 1
                            if state["reset"][1] not in (H3_REQUEST_CANCELLED, 0x10B, 0x100):
                                raise AssertionError(f"stream {sid} reset by server with 0x{state['reset'][1]:x}")
                        continue
                    if client.terminated:
                        raise AssertionError(f"connection terminated: {client.terminated}")
                    if kind == "range" and state["status"] != 206:
                        raise AssertionError(f"stream {sid} range status {state['status']}")
                    if bytes(state["body"]) != body:
                        raise AssertionError(f"stream {sid} {kind}: {len(state['body'])} of {len(body)} bytes; status {state['status']}")
        except Exception as error:  # A failed invariant is a finding with a replayable seed.
            return {"result": "FAIL", "seed": seed, "iteration": iteration, "error": f"{type(error).__name__}: {error}", "log": log}
        if (iteration + 1) % max(1, iterations // 5) == 0:
            health = await healthy(session)
            if health:
                return {"result": "FAIL", "seed": seed, "iteration": iteration, "error": "unhealthy: " + health}
    after = await settle(session, stats_port) if stats_port else None
    report = {"result": "PASS", "seed": seed, "iterations": iterations, "totals": totals, "stats_before": before, "stats_after": after}
    if before and after:
        report["handleGrowth"] = after["handles"] - before["handles"]
        report["managedGrowth"] = after["managedBytes"] - before["managedBytes"]
        if after["activeHandlers"] or report["handleGrowth"] > 64 or report["managedGrowth"] > 32 << 20:
            report["result"] = "FAIL"
            report["error"] = "resources did not settle"
    return report


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=["cases", "fuzz"])
    parser.add_argument("--host", default="localhost")
    parser.add_argument("--port", type=int, required=True)
    parser.add_argument("--stats-port", type=int)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--iterations", type=int, default=100)
    parser.add_argument("--out")
    parser.add_argument("--only", help="run only cases whose id contains this text")
    args = parser.parse_args()
    global ONLY
    ONLY = args.only
    session = Session(args.host, args.port)
    import aioquic
    identity = {"aioquic": aioquic.__version__, "python": sys.version, "target": f"{args.host}:{args.port}"}
    if args.mode == "cases":
        report = asyncio.run(run_cases(session, args.stats_port))
        failed = any(o["result"] in ("violation", "error") for o in report["outcomes"])
    else:
        report = asyncio.run(run_fuzz(session, args.seed, args.iterations, args.stats_port))
        failed = report["result"] != "PASS"
        print(json.dumps(report)[:4000])
    report["identity"] = identity
    if args.out:
        with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(report, handle, indent=1, ensure_ascii=True)
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
