using EmbedIO.Net.Internal.Http2;

namespace EmbedIO.Net.Internal.Http3
{
    internal static class QpackStaticTable
    {
        // RFC 9204 Appendix A. Copyright (c) 2022 IETF Trust and the persons
        // identified as the document authors; see the LICENSE code-components notice.
        internal static readonly HpackField[] Entries =
        {
            new HpackField(":authority", ""),
            new HpackField(":path", "/"),
            new HpackField("age", "0"),
            new HpackField("content-disposition", ""),
            new HpackField("content-length", "0"),
            new HpackField("cookie", ""),
            new HpackField("date", ""),
            new HpackField("etag", ""),
            new HpackField("if-modified-since", ""),
            new HpackField("if-none-match", ""),
            new HpackField("last-modified", ""),
            new HpackField("link", ""),
            new HpackField("location", ""),
            new HpackField("referer", ""),
            new HpackField("set-cookie", ""),
            new HpackField(":method", "CONNECT"),
            new HpackField(":method", "DELETE"),
            new HpackField(":method", "GET"),
            new HpackField(":method", "HEAD"),
            new HpackField(":method", "OPTIONS"),
            new HpackField(":method", "POST"),
            new HpackField(":method", "PUT"),
            new HpackField(":scheme", "http"),
            new HpackField(":scheme", "https"),
            new HpackField(":status", "103"),
            new HpackField(":status", "200"),
            new HpackField(":status", "304"),
            new HpackField(":status", "404"),
            new HpackField(":status", "503"),
            new HpackField("accept", "*/*"),
            new HpackField("accept", "application/dns-message"),
            new HpackField("accept-encoding", "gzip, deflate, br"),
            new HpackField("accept-ranges", "bytes"),
            new HpackField("access-control-allow-headers", "cache-control"),
            new HpackField("access-control-allow-headers", "content-type"),
            new HpackField("access-control-allow-origin", "*"),
            new HpackField("cache-control", "max-age=0"),
            new HpackField("cache-control", "max-age=2592000"),
            new HpackField("cache-control", "max-age=604800"),
            new HpackField("cache-control", "no-cache"),
            new HpackField("cache-control", "no-store"),
            new HpackField("cache-control", "public, max-age=31536000"),
            new HpackField("content-encoding", "br"),
            new HpackField("content-encoding", "gzip"),
            new HpackField("content-type", "application/dns-message"),
            new HpackField("content-type", "application/javascript"),
            new HpackField("content-type", "application/json"),
            new HpackField("content-type", "application/x-www-form-urlencoded"),
            new HpackField("content-type", "image/gif"),
            new HpackField("content-type", "image/jpeg"),
            new HpackField("content-type", "image/png"),
            new HpackField("content-type", "text/css"),
            new HpackField("content-type", "text/html; charset=utf-8"),
            new HpackField("content-type", "text/plain"),
            new HpackField("content-type", "text/plain;charset=utf-8"),
            new HpackField("range", "bytes=0-"),
            new HpackField("strict-transport-security", "max-age=31536000"),
            new HpackField("strict-transport-security", "max-age=31536000; includesubdomains"),
            new HpackField("strict-transport-security", "max-age=31536000; includesubdomains; preload"),
            new HpackField("vary", "accept-encoding"),
            new HpackField("vary", "origin"),
            new HpackField("x-content-type-options", "nosniff"),
            new HpackField("x-xss-protection", "1; mode=block"),
            new HpackField(":status", "100"),
            new HpackField(":status", "204"),
            new HpackField(":status", "206"),
            new HpackField(":status", "302"),
            new HpackField(":status", "400"),
            new HpackField(":status", "403"),
            new HpackField(":status", "421"),
            new HpackField(":status", "425"),
            new HpackField(":status", "500"),
            new HpackField("accept-language", ""),
            new HpackField("access-control-allow-credentials", "FALSE"),
            new HpackField("access-control-allow-credentials", "TRUE"),
            new HpackField("access-control-allow-headers", "*"),
            new HpackField("access-control-allow-methods", "get"),
            new HpackField("access-control-allow-methods", "get, post, options"),
            new HpackField("access-control-allow-methods", "options"),
            new HpackField("access-control-expose-headers", "content-length"),
            new HpackField("access-control-request-headers", "content-type"),
            new HpackField("access-control-request-method", "get"),
            new HpackField("access-control-request-method", "post"),
            new HpackField("alt-svc", "clear"),
            new HpackField("authorization", ""),
            new HpackField("content-security-policy", "script-src 'none'; object-src 'none'; base-uri 'none'"),
            new HpackField("early-data", "1"),
            new HpackField("expect-ct", ""),
            new HpackField("forwarded", ""),
            new HpackField("if-range", ""),
            new HpackField("origin", ""),
            new HpackField("purpose", "prefetch"),
            new HpackField("server", ""),
            new HpackField("timing-allow-origin", "*"),
            new HpackField("upgrade-insecure-requests", "1"),
            new HpackField("user-agent", ""),
            new HpackField("x-forwarded-for", ""),
            new HpackField("x-frame-options", "deny"),
            new HpackField("x-frame-options", "sameorigin"),
        };
    }
}
